---
- name: Capture System Information
  hosts: all
  gather_facts: true
  become: yes
  become_user: coreadm
  tasks:
    - name: Get hostname
      shell: hostname
      register: vname

    - name: Remove python36 packages
      yum:
        name: "python36-*"
        state: absent
      ignore_errors: yes


    - name: Create directory "rocky" with specific owner, group, and permissions
      file:
        path: "/tmp/rocky"
        state: directory
        owner: coreadm
        group: coreadm
        mode: "0777"
        
    - name: Remove txtfile and json files
      file:
        path: "/tmp/rocky/{{ item }}"
        state: absent
      with_items:
        - "*.txt"
        - "*.json"
      delegate_to: localhost
      ignore_errors: yes


    - name: Get tcp_keepalive_time
      shell: "cat /etc/sysctl.conf | grep -E '^net.ipv4.tcp_keepalive_time=' | awk -F'=' '{print $2}' || true"
      register: tcp_keepalive_time
      failed_when: false

    - name: Get app size
      shell: df -h /app | grep "/app" | awk '{print $2}'
      register: app_size

    - name: Get swap information
      shell: free -g | grep -i "swap" | awk '{print $1, $2, $3, $4, $5, $6}'
      register: swap

    - name: Get gpgcheck
      shell: cat /etc/yum.conf | grep gpgcheck | awk '{print $2}'
      register: gpgcheck

    - name: Get coreadm limits from limits.conf
      shell: cat /etc/security/limits.conf | grep -i "coreadm"
      register: coreadm_limits_conf

    - name: Check if opens-osqueryd service is running
      shell: systemctl is-active opens-osqueryd
      register: osqueryd_service_status
      ignore_errors: true

    - name: Display status
      debug:
        msg: "osqueryd is {{ 'running' if osqueryd_service_status.rc == 0 else 'not running' }}"

    - name: Check if uptycs service is running
      shell: systemctl is-active osquery
      register: uptycs_service_status
      ignore_errors: true

    - name: Display status
      debug:
        msg: "uptycs is {{ 'running' if uptycs_service_status.rc == 0 else 'not running' }}"


    - name: Get ulimit for open files
      shell: ulimit -n
      register: open_files_ulimit
      become_user: coreadm

    - name: Get ulimit for max user processes
      shell: ulimit -u
      register: max_user_processes_ulimit
      become_user: coreadm

    - name: Get kernel version
      shell: uname -r
      register: kernel

    - name: Get OS release information
      #shell: cat /etc/os-release | grep -E 'ID=|VERSION_ID=' | grep -v 'PLATFORM_ID'
      shell: cat /etc/centos-release
      register: os_release

    - name: Check if "jump" exists in /usr/local/bin
      shell: ls /usr/local/bin | grep "jump"
      register: jump

    - name: Check if "vault" exists in /usr/local/sbin
      shell: ls /usr/local/sbin | grep "vault" || true
      register: vault

    - name: Get root partition size
      shell: df -h /root | tail -n 1 | awk '{print $2}'
      register: root_size
    
    - name: Write output to JSON file new
      copy:
        dest: "/tmp/rocky/pre-{{ vname.stdout }}.json"
        content: |
          {
            "pre-vname": "{{ vname.stdout | default('') | to_json | regex_replace('\"', '') }}",
            "pre_upgrade": {
              "tcp_keepalive_time": "{{ tcp_keepalive_time.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "app_size": "{{ app_size.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "swap": "{{ swap.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "gpgcheck": "{{ gpgcheck.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "coreadm_limits_conf": "{{ coreadm_limits_conf.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "open_files_ulimit": "{{ open_files_ulimit.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "max_user_processes_ulimit": "{{ max_user_processes_ulimit.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "kernel": "{{ kernel.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "os-release": "{{ os_release.stdout | default('') | regex_replace('\"', '') }}"
              "jump": "{{ 'yes' if jump.stdout else 'no' }}",
              "vault": "{{ 'yes' if vault.stdout else 'no' }}",
              "root_size": "{{ root_size.stdout | default('') | to_json | regex_replace('\"', '') }}",
              "pre-opens": "{{ 'yes' if osqueryd_service_status.stdout == 'active' else 'no' }}",
              "pre-uptycs": "{{ 'yes' if uptycs_service_status.stdout == 'active' else 'no' }}"
           }
          }

            
    - debug:
        var: ansible_failed_result      

    - name: Check for merged JSON files
      #shell: ls /tmp/rocky/merged*.json
      shell: ls /tmp/rocky/pre*.json
      args:
        chdir: /tmp/rocky/
      become: yes
      register: ls_output

    - name: Display ls command output
      debug:
         var: ls_output.stdout_lines

      
    - name: Grep command
      #shell: grep -E 'pre-vname|pre-opens|pre-uptycs' /tmp/rocky/merged*.json > package.txt
      #shell: grep -E 'pre-vname|pre-opens|pre-uptycs' /tmp/rocky/pre*.json > {{ vname.stdout_lines }}.txt
      shell: grep -E 'pre-vname|pre-opens|pre-uptycs' /tmp/rocky/pre*.json > "/tmp/rocky/{{ vname.stdout_lines | first }}.txt"
     
      args:
         chdir: /tmp/rocky/
      become: yes   

    - name: Fetch *.txt files to local path
      find:
        paths: /tmp/rocky/
        recurse: yes
        patterns: '*.txt'
      register: txt_files

    - debug:
        msg: "{{ txt_files }}"

  

    - name: Set full permissions for the text files
      file:
        path: "{{ item.path }}"
        mode: "0777"
        owner: coreadm
        group: coreadm
      with_items: "{{ txt_files.files }}"
          

    - name: Fetch pkg txt_filesfrom target servers
      fetch:
        src: "{{ item.path }}"
        dest: "{{ WORKSPACE }}/"
        #dest: /ansible/app/platform/patch_val-test/
        flat: yes
        fail_on_missing: no
      with_items: "{{ txt_files.files }}"  
      #delegate_to: localhost
      ignore_errors: yes
    
    
    - name: Merge all individual server text files
      shell: cat "{{ WORKSPACE }}"/*comcast.net.txt > "{{ WORKSPACE }}/final-merged_file.txt"
      args:
        chdir: "{{ WORKSPACE }}"
      delegate_to: localhost 

    
    - name: Set full permissions for the merged file
      file:
        path: "{{ WORKSPACE }}/final-merged_file.txt"
        mode: "0777"
        owner: coreadm
        group: coreadm
      delegate_to: localhost 

    
